### ISSUE TITLE
Add SQL ORM

### ISSUE THREAD

**Issue by FoksVHox** [LuaPlusPlus/lua-plus-plus#17]
Add an easy way to support, mysqloo, tmysql & mysqlite!

**Comment by JustPlayerDE** [comment]
its the job of a library, not a transpiler

**Comment by TomDotBat** [comment]
All of these libraries work out of the box. As far as we are aware, anything in plain Lua/gLua will work with Lua++.

**Comment by FoksVHox** [comment]
It sure does, however, it is a pain in the ass to create tables, and therefore I'm requesting this. @TomDotBat

**Comment by TomDotBat** [comment]
@FoksVHox What do you mean by "creating tables"? Would that be creating a table in MySQL?

**Comment by FoksVHox** [comment]
Yes, indeed.

**Comment by JustPlayerDE** [comment]
and Again: this is a transpiler, not a library 

if you want something that helps you with SQL use a library or create your own.

**Comment by TomDotBat** [comment]
Yes, as @JustPlayerDE said. This is a transpiler, you can use a MySQL library for that.

**Comment by FoksVHox** [comment]
I know that LPP is a transpiler, but I still think it should be added. In comparison with luax, I believe that it is also a transpiler, yet it has these things.

**Comment by TomDotBat** [comment]
I believe Xenin framework has its own SQL library. Which is pretty the much the same as using an existing one.

**Comment by NoSharp** [comment]
I think this might be a separate system that I might undertake soon, A library written in L++ of course.

**Comment by FoksVHox** [comment]
@TomDotBat I've tried to find it, but as far as I know it is only in luax...

@NoSharp Sounds great would it be something that we could find on the LPP team?

**Comment by NoSharp** [comment]
Yes, It might be a good way to get attention for LPP :P

**Comment by JustPlayerDE** [comment]
@FoksVHox the database stuff is in the Xenin Framework: https://gitlab.com/sleeppyy/xeninui/-/tree/master/lua/xeninui/server

there is some stuff written _with laux_ but its not _in laux_

**Comment by TomDotBat** [comment]
> @FoksVHox the database stuff is in the Xenin Framework: https://gitlab.com/sleeppyy/xeninui/-/tree/master/lua/xeninui/server
> 
> there is some stuff written _with laux_ but its not _in laux_

Yes this is what I was speaking of, thanks @JustPlayerDE.
