### ISSUE TITLE
Type checking

### ISSUE THREAD

**Issue by TomDotBat** [LuaPlusPlus/lua-plus-plus#22]
### **Idea**
Implement an `as` keyword to function arguments.

### **What will it do?**
Using the as keyword on a function argument will require you to put a type after, for example "string".
What this will do is automatically create an assert if the specified argument is not the type that was expected.

### **Example**
**Lua++**
```lua
local function isNameShort(name as string) --Returns whether the name is less than 5 chars
    return #name < 5
end
```

**Lua (Transpiled Code)**
```lua
local function isNameShort(name)
    assert(type(name) == "string", "name expected type string!")

    return #name < 5
end
```

**Comment by NoSharp** [comment]
*basically what we did in skeypads 😛*

**Comment by TomDotBat** [comment]
Exactly like that, just with about 200 less lines of code.

**Comment by FoksVHox** [comment]
Instead of implementing ```as``` as a keyword couldn’t it just be done like this?

```Lua

local function isNameShort(String name) --Returns whether the name is less than 5 chars
    return #name < 5
end
```

**Comment by TomDotBat** [comment]
Could be, but the way I was thinking would probably be easier to implement.
Checking for the keyword `as` after a function argument then plugging the word after into the type check.

**Comment by FoksVHox** [comment]
Maybe, I just think that ```as``` should be kept for thing like use statement if that got implemented.
